theme: jekyll-theme-primer
title: Automatic Playlist Recommender
description: Build a music recommender system for song discovery
baseurl:
markdown: kramdown
kramdown:
		math_engine: mathjax
		input: GFM
		syntax_highlighter: rouge
